version: '3'

services:

  opensearch:
    container_name: django_elasticsearch_dsl_drf_opensearch_2
    build:
      context: .
      dockerfile: ./docker/opensearch/Dockerfile_2
    volumes:
    - osdata2:/usr/share/opensearch/data
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
#    - bootstrap.memory_lock=true
    - discovery.type=single-node
    - cluster.routing.allocation.disk.watermark.low=97%
    - cluster.routing.allocation.disk.watermark.high=98%
    - cluster.routing.allocation.disk.watermark.flood_stage=99%
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

volumes:
  osdata2:
