name: test opensearch

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        es-version: ['1', '2']
        include:

        - python-version: 3.7
          tox_env: py37-django22-opensearch2
          requirements: django_2_2
        - python-version: 3.7
          tox_env: py37-django31-opensearch2
          requirements: django_3_1
        - python-version: 3.7
          tox_env: py37-django32-opensearch2
          requirements: django_3_2

        - python-version: 3.7
          tox_env: py37-django22-opensearch1
          requirements: django_2_2
        - python-version: 3.7
          tox_env: py37-django31-opensearch1
          requirements: django_3_1
        - python-version: 3.7
          tox_env: py37-django32-opensearch1
          requirements: django_3_2

        - python-version: 3.8
          tox_env: py38-django22-opensearch2
          requirements: django_2_2
        - python-version: 3.8
          tox_env: py38-django31-opensearch2
          requirements: django_3_1
        - python-version: 3.8
          tox_env: py38-django32-opensearch2
          requirements: django_3_2

        - python-version: 3.8
          tox_env: py38-django22-opensearch1
          requirements: django_2_2
        - python-version: 3.8
          tox_env: py38-django31-opensearch1
          requirements: django_3_1
        - python-version: 3.8
          tox_env: py38-django32-opensearch1
          requirements: django_3_2

        - python-version: 3.9
          tox_env: py39-django22-opensearch2
          requirements: django_2_2
        - python-version: 3.9
          tox_env: py39-django31-opensearch2
          requirements: django_3_1
        - python-version: 3.9
          tox_env: py39-django32-opensearch2
          requirements: django_3_2

        - python-version: 3.9
          tox_env: py39-django22-opensearch1
          requirements: django_2_2
        - python-version: 3.9
          tox_env: py39-django31-opensearch1
          requirements: django_3_1
        - python-version: 3.9
          tox_env: py39-django32-opensearch1
          requirements: django_3_2

        - python-version: '3.10'
          tox_env: py310-django22-opensearch2
          requirements: django_2_2
        - python-version: '3.10'
          tox_env: py310-django31-opensearch2
          requirements: django_3_1
        - python-version: '3.10'
          tox_env: py310-django32-opensearch2
          requirements: django_3_2

        - python-version: '3.10'
          tox_env: py310-django22-opensearch1
          requirements: django_2_2
        - python-version: '3.10'
          tox_env: py310-django31-opensearch1
          requirements: django_3_1
        - python-version: '3.10'
          tox_env: py310-django32-opensearch1
          requirements: django_3_2

    services:
      elasticsearch:
        image: opensearchproject/opensearch:${{ matrix.es-version }}
        ports:
          - 9200:9200
        options: >-
          -e="http.host=0.0.0.0"
          -e="transport.host=127.0.0.1"
          -e="discovery.type=single-node"
          -e="plugins.security.disabled=true"
          --health-cmd="curl http://localhost:9200/_cluster/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pip-tools
        python -m pip install tox
        pip-compile examples/requirements/${{ matrix.requirements }}.in
        pip-compile examples/requirements/opensearch_${{ matrix.es-version }}x.in
        pip-compile examples/requirements/test.in
        python -m pip install -r examples/requirements/${{ matrix.requirements }}.txt
        python -m pip install -r examples/requirements/opensearch_${{ matrix.es-version }}x.txt
        python -m pip install -r examples/requirements/test.txt
    - name: Run tests
      uses: nick-invision/retry@v2
      with:
        command: tox -e ${{ matrix.tox_env }} -c tox_opensearch.ini -- --color yes
        timeout_minutes: 15
        max_attempts: 3
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Run Tests

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
        debug: True
